---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: template
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - type: containerfile
    snippets:
      # Step 1: Install build tools PLUS curl and unzip
      - RUN rpm-ostree install -y kernel-modules kernel-devel gcc make curl unzip git

  - type: containerfile
    snippets:
      # Step 2: Download ZIP, unzip, build, and install
      - |
        RUN set -eux && \
            # Find kernel versions
            KVER_MOD=$(rpm -q kernel-modules --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}') && \
            KVER_DEVEL=$(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}') && \
            echo "--- Found Kernel-Modules Version: ${KVER_MOD} ---" && \
            echo "--- Found Kernel-Devel Version: ${KVER_DEVEL} ---" && \
            
            # Set kernel source directory
            KDIR="/usr/src/kernels/${KVER_DEVEL}" && \
            echo "--- Using Kernel Build Path: ${KDIR} ---" && \
            
            # Verify paths exist
            ls -ld ${KDIR} && \
            ls -ld /lib/modules/${KVER_MOD} && \
            
            # *** 여기가 수정된 부분입니다 ***
            # Download the ZIP archive of the main branch using curl with -L to follow redirects
            curl -L https://github.com/morrownr/rtl8852bu/archive/refs/heads/main.zip -o /tmp/rtl8852bu.zip && \
            # Unzip the archive into /tmp
            unzip /tmp/rtl8852bu.zip -d /tmp && \
            # Change directory into the unzipped folder (usually repo name + branch name)
            cd /tmp/rtl8852bu-main && \
            
            # Build using the kernel source directory
            make -C ${KDIR} M=$(pwd) modules && \
            make -C ${KDIR} M=$(pwd) install && \
            
            # Update module dependencies for the correct kernel module version
            depmod -a ${KVER_MOD} && \
            
            # Clean up temporary files/folders
            rm -rf /tmp/rtl8852bu-main /tmp/rtl8852bu.zip

