---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: template
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - type: containerfile
    snippets:
      # 1단계: *** 여기가 수정된 부분입니다 ***
      # Bazzite의 "실행 중인" 커널과 "정확히 일치하는" 패키지들을 설치합니다.
      - RUN rpm-ostree install -y \
            kernel-modules-6.16.4-166.bazzite.fc42.x86_64 \
            kernel-devel-6.16.4-166.bazzite.fc42.x86_64 \
            gcc make git

      # 2단계: 하드코딩된 커널 버전으로 빌드합니다.
      - |
        RUN set -eux && \
            # Bazzite 커널 버전을 하드코딩합니다.
            KVER="6.16.4-166.bazzite.fc42.x86_64" && \
            echo "--- Building for specific Kernel Version: ${KVER} ---" && \
            
            KDIR="/usr/src/kernels/${KVER}" && \
            echo "--- Using Kernel Build Path: ${KDIR} ---" && \
            
            # 두 경로가 모두 존재하는지 확인합니다.
            ls -ld ${KDIR} && \
            ls -ld /lib/modules/${KVER} && \
            
            git clone https://github.com/morrownr/rtl8852bu-20240418.git /tmp/rtl8852bu && \
            cd /tmp/rtl8852bu && \
            
            make -C ${KDIR} M=$(pwd) modules && \
            make -C ${KDIR} M=$(pwd) install && \
            
            depmod -a ${KVER} && \
            
            rm -rf /tmp/rtl8852bu
